-- MySQL Script generated by MySQL Workbench
-- 05/11/15 18:29:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jp7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jp7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jp7` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `jp7` ;

-- -----------------------------------------------------
-- Table `jp7`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp7`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchaser_name` VARCHAR(256) NOT NULL,
  `item_description` VARCHAR(256) NOT NULL,
  `item_price` FLOAT NOT NULL,
  `purchase_count` INT NOT NULL,
  `merchant_addres` VARCHAR(256) NOT NULL,
  `merchant_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
